# Generated by Django 5.1.5 on 2025-01-27 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmaciaa', '0002_entrega_pedido_remove_farmacia_sucursales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='cantidad_disponible',
        ),
        migrations.CreateModel(
            name='InventarioSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disponible', models.IntegerField()),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_sucursal', to='Farmaciaa.medicamento')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='Farmaciaa.sucursal')),
            ],
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
