# Generated by Django 5.1.5 on 2025-01-27 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmaciaa', '0004_transferencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionEntregaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(choices=[('RETIRO_EN_SUCURSAL', 'Retiro en Sucursal'), ('ENVIO_DESDE_ORIGEN', 'Envío desde Sucursal de Origen')], max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='inventariosucursal',
            old_name='cantidad_disponible',
            new_name='cantidad',
        ),
        migrations.AddField(
            model_name='entrega',
            name='pedido',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='Farmaciaa.pedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Farmaciaa.cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='opcion_entrega',
            field=models.CharField(choices=[('RETIRO_EN_SUCURSAL', 'Retiro en Sucursal'), ('ENVIO_DESDE_ORIGEN', 'Envío desde Sucursal de Origen')], default='RETIRO_EN_SUCURSAL', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='sucursal_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_entrega', to='Farmaciaa.sucursal'),
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farmaciaa.direccion'),
        ),
        migrations.AlterField(
            model_name='inventariosucursal',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farmaciaa.medicamento'),
        ),
        migrations.AlterField(
            model_name='inventariosucursal',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='Farmaciaa.sucursal'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado'), ('EN_PROCESO', 'En proceso')], default='EN_PROCESO', max_length=20),
        ),
    ]
